version: V4
log_level: Info
port_range_start: 4200
ip: 127.0.0.1
env: {}
root_dir: "~"
default_log_format: standard
auto_start: true
acme: null
admin_api_host: null
admin_api_password: null

backends:

  py.localtest.me:
    type: process
    bin: /usr/bin/python3

    args:
      - -m
      - http.server
      - $port

    dir: $cfg_dir
    env: {}
    protocol: h1
    https: false
    port: 8012
    auto_start: null
    exclude_from_start_all: false
    log_level: null
    log_format: null

  lobsters.localtest.me:
    type: remote

    endpoints:

      - addr: lobste.rs
        port: 443

      - addr: lobsters.dev
        port: 443

    protocol: h1
    https: true
    keep_original_host_header: false

frontends:

  http:
    port: 8080

    routes:
      py.localtest.me: py.localtest.me
      lobsters.localtest.me: lobsters.localtest.me

  https:
    port: 4343
    cert: self_signed
    routes: inherit
