name: BuildAndTest
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout cruma-sdk
        uses: actions/checkout@v4
        with:
          repository: umbra-yurei/cruma-sdk
          path: cruma-sdk
          token: ${{ secrets.CRUMA_SDK_TOKEN }}

      - uses: dtolnay/rust-toolchain@nightly

      - run: cargo test --all-features
